karhoo/karhoo-android-ui-sdk

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/BookingPaymentMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/BookingPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/BookingPaymentView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/BookingPaymentPresenterTest.kt
[MOB-2713](https://karhoo.atlassian.net/browse/MOB-2713)
=> [MOB-2713] Identify payment providers

app/src/androidTest/java/com/karhoo/karhootraveller/common/PreferencesRobot.kt
[MOB-2926](https://karhoo.atlassian.net/browse/MOB-2926)
Added extra mocking requirement
=> Mob 2926 fix failing profile tests

uisdk/src/main/res/layout/uisdk_view_address_picker.xml
[MOB-2929](https://karhoo.atlassian.net/browse/MOB-2929)
Just made the text for the lower date text to be ever so slightly smaller. Still readable and now fits as well even with large enough dates.
=> [MOB-2929] Date now fits

.circleci/config.yml, app/src/main/res/values/styles.xml, scripts/environmentSetup.sh, uisdk/build.gradle, uisdk/src/main/AndroidManifest.xml, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInService.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/ResultActivity.kt, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-2715](https://karhoo.atlassian.net/browse/MOB-2715)
Integrate Drop In
N/a
=> Adyen drop in integration

app/src/main/res/layout/view_splash.xml, app/src/main/res/values/styles.xml, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/contact/ContactOptionsView.kt, uisdk/src/main/res/layout/uisdk_view_contact_options.xml, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/values/style_text.xml, uisdk/src/main/res/values/styles.xml
[MOB-2946](https://karhoo.atlassian.net/browse/MOB-2946)
Fixing colours. Still got 2 colour issues within, but created a whole new ticket for that in the sprint, might take far longer to fix.
Fixes are a bit messy, but it seems to be how MaterialComponents works at this current time. Any cleanup suggestions would be helpful.
=> [MOB-2946] Fix colors with usage of MaterialComponents

app/src/androidTest/java/com/karhoo/karhootraveller/util/TestData.kt, uisdk/build.gradle, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt
Fix TestData which caused issues for tests not running
=> [MOB-XXXX] Unit test fix

uisdk/src/main/res/layout/uisdk_view_address_result_item.xml
[MOB-1503](https://karhoo.atlassian.net/browse/MOB-1503)
=> [MOB-1503] Quick fix for a bug on airport address

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationView.kt
This is the last of the broken AlertDialogs that are broken. 
=> [MOB-XXXX] More dialog fixes for the app

app/src/main/java/com/karhoo/karhootraveller/KarhooConfig.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/AdyenBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestSDKConfig.kt, uisdk/src/main/java/com/karhoo/uisdk/BraintreeConfig.kt, uisdk/src/main/java/com/karhoo/uisdk/KarhooUISDKConfiguration.kt, uisdk/src/main/java/com/karhoo/uisdk/PaymentProviderConfig.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/braintree/BraintreePaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/UnitTestUISDKConfig.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenterTest.kt
[MOB-2965](https://karhoo.atlassian.net/browse/MOB-2965)
Minor refectoring to fix Adyen UI test
=> Mob 2965 fix adyen ui tests

app/src/androidTest/java/com/karhoo/karhootraveller/common/PreferencesRobot.kt, app/src/androidTest/java/com/karhoo/karhootraveller/menu/MenuTests.kt, app/src/androidTest/java/com/karhoo/karhootraveller/profile/user/UserProfileRobot.kt, app/src/androidTest/java/com/karhoo/karhootraveller/profile/user/UserProfileTests.kt, app/src/androidTest/java/com/karhoo/karhootraveller/splash/SplashTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/address/AddressTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/AdyenBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingFlowTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/GuestBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/rides/RidesFlowTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/rides/RidesTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripFlowTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentPresenter.kt
Fixed tests and created next test for Adyen user profile, it is Ignored for now as fix is needed on a bug.
=> Ui test profile adyen

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/supplier/BookingSupplierViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/supplier/BookingSupplierViewModel.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/supplier/SupplierListPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/supplier/SupplierListView.kt, uisdk/src/main/res/layout/uisdk_activity_booking_content.xml, uisdk/src/main/res/layout/uisdk_view_booking_map.xml, uisdk/src/main/res/layout/uisdk_view_supplier.xml, uisdk/src/main/res/values/dimens.xml
[MOB-2974](https://karhoo.atlassian.net/browse/MOB-2974)
Move Locate Me button into the Booking Map View.
N/a
=> MOB-2974 - Move locate me button

app/src/main/java/com/karhoo/karhootraveller/presentation/login/email/EmailDialog.kt, app/src/main/java/com/karhoo/karhootraveller/presentation/splash/SplashActivity.kt, app/src/main/java/com/karhoo/karhootraveller/presentation/web/KarhooWebActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/base/BaseActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/BookingStatusView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/web/KarhooWebView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/web/WebActivity.kt, uisdk/src/main/res/values/styles.xml
[MOB-3019](https://karhoo.atlassian.net/browse/MOB-3019)
Just a really quick fix for invisible buttons on alert dialog and removed AlertDialog due to it becoming redundant. 
=> [MOB-3019] Quick fix for invisible alerts

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/supplier/BookingSupplierViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/supplier/AvailabilityProvider.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/supplier/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/supplier/SupplierListMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/supplier/SupplierListPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/supplier/SupplierListView.kt, uisdk/src/main/res/values/dimens.xml
[MOB-2977](https://karhoo.atlassian.net/browse/MOB-2977)
Move KarhooAvailability setup to SupplierListView
=> MOB-2977 remove quote list availability dependency

uisdk/src/androidTest/java/com/karhoo/uisdk/booking/adyen/AdyenBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/braintree/BraintreeBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt
=> Fixed failing tests

uisdk/build.gradle, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerPresenterTest.kt
[MOB-3027](https://karhoo.atlassian.net/browse/MOB-3027)
Only make the call to retrieve the payment provider if there is an organisation for the user
N/a
=> MOB-3027 - Fix guest checkout payment provider call crash

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/res/values/colors.xml
MOB-XXXX
Add primaryColor to enable Adyen customisation
=> MOB-XXXX - Fix Adyen primary colour

.circleci/config.yml, app/build.gradle, app/src/main/java/com/karhoo/karhootraveller/presentation/splash/register/SplashMVP.kt, app/src/main/java/com/karhoo/karhootraveller/presentation/splash/register/SplashPresenter.kt, app/src/main/java/com/karhoo/karhootraveller/presentation/splash/register/SplashScreenView.kt, app/src/test/java/com/karhoo/karhootraveller/presentation/splash/register/SplashPresenterTest.kt
[MOB-2913](https://karhoo.atlassian.net/browse/MOB-2913)
=> [MOB-2913] Token

app/build.gradle, uisdk/build.gradle, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ServerRobot.kt
Updated dependencies to fix failing tests.
=> Updated dependencies to fix failing tests.

app/build.gradle
[MOB-3054](https://karhoo.atlassian.net/browse/MOB-3054)
Sandbox release for Adyen UAT (FinOps)
=> MOB-3054 Sandbox release for FinOps Adyen UAT

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/PaymentActions.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/bookingrequest/BookingRequestStateViewModel.kt
[MOB-2975](https://karhoo.atlassian.net/browse/MOB-2975)
Fix the bug where terms and conditions are not launching by adding a new action.
N/a
=> MOB-2975 - Fix T&Cs bug

uisdk/src/main/res/layout/uisdk_view_booking_terms.xml
[MOB-3025](https://karhoo.atlassian.net/browse/MOB-3025)
Changed hardcoded strings to use actual strings, changed constraints to make things look nice in all screens sizes.
=> Mob 3025 translations fix

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt
[MOB-3060](https://karhoo.atlassian.net/browse/MOB-3060)
Tweak Adyen drop-in logic to fix bug when there is a challenge result in the payments-details response.
N/a
=> MOB-3060 - Fix adyen 3ds

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenterTest.kt
[MOB-3057](https://karhoo.atlassian.net/browse/MOB-3057)
Add 3ds to additionalData in payments request
N/a
=> MOB-3057 - Add 3ds to payment request

app/src/androidTest/java/com/karhoo/karhootraveller/common/PreferencesRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ServerRobot.kt
Fixed UI tests by adding Delete refresh token function
=> Fix failing ui tests

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenterTest.kt
[MOB-3057](https://karhoo.atlassian.net/browse/MOB-3057)
Change allow3DS2 value from Boolean to String
N/a
=> MOB-3057 - 3ds additionalData fix

app/build.gradle
[MOB-3053](https://karhoo.atlassian.net/browse/MOB-3053)
Sandbox release for Adyen UAT (FinOps) with Adyen 3ds fix
=> MOB-3054 - Sandbox release for Adyen UAT (FinOps) with Adyen 3ds fix

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt
[MOB-3070](https://karhoo.atlassian.net/browse/MOB-3070)
Add meta field to the TripBooking request
N/a
=> MOB-3070 - Add TripBooking meta element

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenterTest.kt
[MOB-3021](https://karhoo.atlassian.net/browse/MOB-3021)
Fix to not display alert when cancelling payment
N/a
=> MOB-3021 - Fix incorrect payment cancellation error

uisdk/build.gradle, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListItemView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt
[MOB-3015](https://karhoo.atlassian.net/browse/MOB-3015)
=> [MOB-3015] Update UISDK to work with updated NSDK

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/deta/DetaPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/eta/EtaPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/map/TripMapPresenterTest.kt
[MOB-3055](https://karhoo.atlassian.net/browse/MOB-3055)
=> [MOB-3055] Make UISDK work with new canary version of NSDK

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenterTest.kt
[MOB-3089](https://karhoo.atlassian.net/browse/MOB-3089)
Updated to use transaction_id field. Will be renamed in next PR.
N/a
=> MOB-3089 - Set trip id from renamed transaction_id field

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInService.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServiceMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenterTest.kt
[MOB-3089](https://karhoo.atlassian.net/browse/MOB-3089)
Rename transaction_id to trip_id.
N/a
=> MOB-3089 - Rename transaction_id to trip_id

uisdk/build.gradle
[MOB-3085](https://karhoo.atlassian.net/browse/MOB-3085)
New UISDK release with Adyen fixes
N/a
=> MOB-3085 - Release 1.1.1 develop

app/build.gradle, uisdk/build.gradle, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/adapter/AddressItemView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/PaymentDropInMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInService.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServiceMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListItemView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/braintree/BraintreePaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/deta/DetaPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/eta/EtaPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/map/TripMapPresenterTest.kt
[MOB-3085](https://karhoo.atlassian.net/browse/MOB-3085)
New UISDK release with Adyen fixes
N/a
=> MOB-3085 - Release 1.1.1 master

app/build.gradle, uisdk/build.gradle
[MOB-3085](https://karhoo.atlassian.net/browse/MOB-3085)
FinOps Adyen UAT Sandbox build with Adyen fixes
N/a
=> MOB-3085 - FinOps Adyen UAT Sandbox build with Adyen fixes

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt
[MOB-3033](https://karhoo.atlassian.net/browse/MOB-3033)
Fix book button enablements and text for token users
N/a
=> MOB-3033 - Token booking bug fixes

uisdk/build.gradle
[MOB-3040](https://karhoo.atlassian.net/browse/MOB-3040)
All works, everything passing
=> [MOB-3040] Bump NSDK version

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentPresenterTest.kt
[MOB-3095](https://karhoo.atlassian.net/browse/MOB-3095)
Only retrieve payment provider if there isn't one stored for the user to stop multiple calls.
N/a
=> MOB-3095 - Only retrieve payment provider if there is none stored

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt
[MOB-3033](https://karhoo.atlassian.net/browse/MOB-3033)
Simplify logic and add unit tests for bug fixes to book button enablement
N/a
=> MOB-3033 - Fix book button for all auth types

build.gradle
[MOB-3041](https://karhoo.atlassian.net/browse/MOB-3041)
=> [MOB-3041] Kotlin 1.4

uisdk/build.gradle
[MOB-3041](https://karhoo.atlassian.net/browse/MOB-3041)
Update the build version and generate binary for Kotlin 1.4 upgrade
N/a
=> MOB-3041 - Kotlin 1.4 version update

uisdk/src/main/res/layout/uisdk_view_quotes_list.xml
[MOB-3116](https://karhoo.atlassian.net/browse/MOB-3116)
=> [MOB-3116] Remove the shadow on quote list

.circleci/config.yml, app/.gitignore, app/build.gradle, app/src/debug/AndroidManifest.xml, app/src/main/java/com/karhoo/karhootraveller/KarhooApplication.kt, app/src/main/java/com/karhoo/karhootraveller/presentation/karhooLabs/KarhooLabsActivity.kt, app/src/main/res/layout/activity_karhoo_labs.xml, app/src/main/res/values/strings.xml, build.gradle
[MOB-3128](https://karhoo.atlassian.net/browse/MOB-3128)
- Configure Firebase and Google Analytics
- Add the dependencies to the project
- Updated the project documentation
Details regarding the secure.properties and google-services.json encode/decode in CircleCI yaml file
https://stackoverflow.com/questions/50662772/circleci-build-fails-because-google-services-json-is-not-present
The team members need to add the Google-services.json to the root folder of the project
Please review the guidelines for contributing to this …
=> Setup Firebase Crashlytics and Analytics

app/src/main/java/com/karhoo/karhootraveller/presentation/splash/register/SplashPresenter.kt, app/src/test/java/com/karhoo/karhootraveller/presentation/splash/register/SplashPresenterTest.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/ProviderType.kt
[MOB-3115](https://karhoo.atlassian.net/browse/MOB-3115)
Only make the get nonce call when the payment provider is Braintree
=> Mob 3115 avoid unnecessery braintree call for adyen

app/src/main/java/com/karhoo/karhootraveller/service/analytics/KarhooAnalytics.kt, uisdk/src/main/java/com/karhoo/uisdk/analytics/Analytics.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/deta/DetaPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/deta/DetaView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/eta/EtaPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/eta/EtaView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/deta/DetaPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/eta/EtaPresenterTest.kt
[MOB-3127](https://karhoo.atlassian.net/browse/MOB-3127)
Remove eta analytics events
=> Remove etaDisplayed and detaDisplayed analytics events

uisdk/src/main/java/com/karhoo/uisdk/screen/address/map/AddressMapView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/map/TripMapView.kt, uisdk/src/main/res/layout/uisdk_view_booking_map.xml, uisdk/src/main/res/values/dimens.xml, uisdk/src/main/res/values/styles.xml
[MOB-3142](https://karhoo.atlassian.net/browse/MOB-3142)
Remove the unnecessery paddings from map pin
=> Remove the unnecessery paddings from map pin

uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt
Fix compilation error on test data file.
=> Test data fix

uisdk/build.gradle
[MOB-3151](https://karhoo.atlassian.net/browse/MOB-3151)
Rebase to master
N/a
=> Rebase to master

.github/delete-merged-branch-config.yml
[MOB-3151](https://karhoo.atlassian.net/browse/MOB-3151)
Rebase develop to master
N/a
=> Rebase develop

app/build.gradle
[MOB-3130](https://karhoo.atlassian.net/browse/MOB-3130)
Update traveller app version
N/a
=> Release 1.12.0

app/release/output.json, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationView.kt, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/test/java/com/karhoo/uisdk/UnitTestUISDKConfig.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/tripallocation/TripAllocationPresenterTest.kt
[MOB-2949](https://karhoo.atlassian.net/browse/MOB-2949)
=> MOB-2949 - Timeout driver allocation

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentView.kt
[MOB-2928](https://karhoo.atlassian.net/browse/MOB-2928)
=> [MOB-2928] Fix edit button on refresh

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/tripallocation/TripAllocationPresenterTest.kt
[MOB-2949](https://karhoo.atlassian.net/browse/MOB-2949)
Take the user to the Ride Details screen when the OK button is clicked on the driver allocation delay alert.
N/a
=> MOB-2949 - Take user to Ride Details screen

uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt
[MOB-3170](https://karhoo.atlassian.net/browse/MOB-3170)
3 tests added to check the notification when change in trip status occurs.
=> Trip status notification UI tests

app/src/androidTest/java/com/karhoo/karhootraveller/testsuites/CombinedTestSuites.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/BaseRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ServerRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/ridedetail/RideDetailRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/ridedetail/RideDetailTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/rides/RidesTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/testsuites/UISDKTestsSuite.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripFlowTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/BookingStatusView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/contact/ContactOptionsActions.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/contact/ContactOptionsView.kt, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenterTest.kt
[MOB-3155](https://karhoo.atlassian.net/browse/MOB-3155)
Added UI tests for cancellation booking fee display plus fixes for main PR 
N/a
=> MOB-3153 - UI tests and fixes

uisdk/build.gradle
=> Update nsdk dependency 

app/src/androidTest/java/com/karhoo/karhootraveller/common/BaseRobot.kt, app/src/androidTest/java/com/karhoo/karhootraveller/profile/user/UserProfileTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingLOCTest.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/braintree/BraintreeBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ServerRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/ridedetail/RideDetailRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/ridedetail/RideDetailTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripTests.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/braintree/BraintreePaymentPresenter.kt
[MOB-3188](https://karhoo.atlassian.net/browse/MOB-3188)
Fix for UI Tests
=> Fix UI Tests

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt
[MOB-3192](https://karhoo.atlassian.net/browse/MOB-3192)
We've been already sending the returnUrl parameter and the value is coming from Adyen utility function `RedirectComponent.getReturnUrl(this)`
=> Remove RETURN_URL_SUFFIX parameter

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenDropInServicePresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentPresenterTest.kt
[MOB-3204](https://karhoo.atlassian.net/browse/MOB-3204)
Enforce Adyen 3DS payments
Display Adyen Error details
=> Enforce Adyen 3DS payments

uisdk/src/androidTest/java/com/karhoo/uisdk/ridedetail/RideDetailRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/rides/RidesTests.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardView.kt, uisdk/src/main/res/layout/uisdk_view_contact_options.xml, uisdk/src/main/res/layout/uisdk_view_upcoming_ride_card.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenterTest.kt
[MOB-3207](https://karhoo.atlassian.net/browse/MOB-3207)
Align the button display on the Trip and Ride screens with iOS. Also some tidying up of layout and renaming.
N/a
=> MOB-3207 - Ride and Trip button alignment

app/src/test/java/com/karhoo/karhootraveller/presentation/splash/register/SplashPresenterTest.kt, uisdk/build.gradle, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/util/Constants.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt
[MOB-3187](https://karhoo.atlassian.net/browse/MOB-3187)
Delete saved payment info when Adyen users leave the Booking Request screen
N/a
=> MOB-3187 - Clear Adyen card info when leaving Booking Request screen 

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/adyen/AdyenPaymentView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/domain/quotes/PriceSortTest.kt
[MOB-3209](https://karhoo.atlassian.net/browse/MOB-3209)
Use fleet model
=> Use fleet model

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/BookingPaymentView.kt
[MOB-3187](https://karhoo.atlassian.net/browse/MOB-3187)
Hide Edit label if the payment info is not available
=> Hide Edit label if the payment info is not available

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/prebookconfirmation/PrebookConfirmationView.kt, uisdk/src/main/res/layout/uisdk_alert_prebook_confirmation.xml
[MOB-3212](https://karhoo.atlassian.net/browse/MOB-3212)
Show the display of 
N/a
=> MOB-3212 - Prebook confirmation scrolling

uisdk/src/androidTest/java/com/karhoo/uisdk/ridedetail/RideDetailTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/Constants.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/ServiceCancellationExt.kt, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/layout/uisdk_view_upcoming_ride_card.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/quotes/BookingQuotesPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenterTest.kt
MOB-3208
MOB-3208 [UI SDK] Display cancellation SLA in the Rides screen
=> MOB-3208 [UI SDK] Display cancellation SLA in the Rides screen

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/quotes/BookingQuotesViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt
[MOB-3214](https://karhoo.atlassian.net/browse/MOB-3214)
Stop polling quotes when leaving the BookingActivity
N/a
=> MOB-3214 - Stop quote polling in onPause

uisdk/src/androidTest/java/com/karhoo/uisdk/booking/GuestBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/quotes/BookingQuotesMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/quotes/BookingQuotesPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/quotes/BookingQuotesView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListItemView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/ServiceCancellationExt.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/quotes/BookingQuotesPresenterTest.kt
MOB-3224
Display SLA Cancellation for BeforeDriverEnRoute
=> Mob 3224 cancellation before driver en route

gradle/wrapper/gradle-wrapper.properties, uisdk/src/main/java/com/karhoo/uisdk/util/DateUtil.kt, uisdk/src/main/java/com/karhoo/uisdk/util/TimeUtil.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/ServiceCancellationExt.kt, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/quotes/BookingQuotesPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/util/ServiceCancellationExtTests.kt
MOB-3238 
MOB-3238 Display cancellation minutes in a user-friendly format
=> MOB-3238 Display cancellation minutes in a user-friendly format

uisdk/src/main/res/layout/uisdk_view_past_ride_card.xml, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/layout/uisdk_view_upcoming_ride_card.xml
[MOB-3023](https://karhoo.atlassian.net/browse/MOB-3023)
Fix truncated long addresses on Upcoming and Past Rides and Ride Details screens
N/a
=> MOB-3023 - Fix truncated long addresses on Upcoming and Past Rides and Ride Details screens

README.md, app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, uisdk/README.md, uisdk/src/main/java/com/karhoo/uisdk/KarhooUISDKConfiguration.kt, uisdk/src/main/java/com/karhoo/uisdk/base/BaseActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/util/Logger.kt, uisdk/src/main/res/values/strings.xml
MOB-3199 Traveller App enters a misconfigured state after a crash
MOB-3199 Traveller App enters a misconfigured state after a crash -added uncaught exception handler, logged error if karhoo uisdk configuration is not set, added logger
=> MOB-3199 Traveller App enters a misconfigured state after a crash

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, app/src/main/java/com/karhoo/samples/uisdk/dropin/config/AdyenGuestConfig.kt, uisdk/build.gradle, uisdk/src/main/res/values/styles.xml
[MOB-3228](https://karhoo.atlassian.net/browse/MOB-3228) FIXES
=> Mob 3228 fixes crash booking flow

uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/layout/uisdk_view_upcoming_ride_card.xml
[MOB-3168](git push --set-upstream origin MOB-3168)
Fix button display on the Rides and Ride Details screen for long button text e.g. in French
=> MOB-3168 - Fix Rides and Ride Details button layout for long button text

app/build.gradle, app/src/androidTest/java/com/karhoo/samples/uisdk/dropin/MainRobot.kt
[MOB-3228](https://karhoo.atlassian.net/browse/MOB-3228) Fix Part 1
=> Mob 3228 fix part 1

uisdk/src/main/res/layout/uisdk_view_contact_options.xml, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml
[MOB-3168](https://karhoo.atlassian.net/browse/MOB-3168)
Tweak style and layout of Cancel/Contact buttons to match the style on the Rides screens
N/a
=> MOB-3168 - Tweak style and layout of Cancel/Contact buttons

README.md, uisdk/build.gradle
[MOB-3215](https://karhoo.atlassian.net/browse/MOB-3215)
=> [MOB-3215] Release 1.3.0 Candidate

README.md, uisdk/build.gradle
[MOB-3215](https://karhoo.atlassian.net/browse/MOB-3215)
=> [MOB-3215] Release 1.3.0 stable (tested)

app/build.gradle, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/util/CurrencyExtensions.kt, uisdk/src/main/res/layout/uisdk_view_quotes_item.xml, uisdk/src/test/java/com/karhoo/uisdk/util/CurrencyExtensionsTest.kt
[MOB-3314](https://karhoo.atlassian.net/browse/MOB-3314)
Hot fix for handling french locale for  Braintree
Update quote list item layout to match iOS
=> MOB-3314 hotfix braintree

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt
https://karhoo.atlassian.net/browse/MOB-3225
Stop polling after leaving the Booking screen
=> MOB-3225 Stop polling after leaving the Booking screen

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt
[MOB-3199](https://karhoo.atlassian.net/browse/MOB-3199)
=> Mob 3199 part 2

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/quotes/mocks/QuotesListViewMock.kt
[MOB-3351(https://karhoo.atlassian.net/browse/MOB-3351)
=> Mob 3351 back button in booking

uisdk/src/main/res/layout/uisdk_view_ride_detail.xml
[MOB-3254](https://karhoo.atlassian.net/browse/MOB-3254)
MOB-3254 Ride details buttons not showing correctly on small devices
=> MOB-3254 Ride details buttons not showing correctly on small devices

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt
[MOB-3351](https://karhoo.atlassian.net/browse/MOB-3351)
=> webview back fix

default-detekt-config.yml, uisdk/src/main/AndroidManifest.xml, uisdk/src/main/java/com/karhoo/uisdk/base/BaseActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/adapter/AddressAdapter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/adapter/AddressItemView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/passengerdetails/PassengerDetailsMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/passengerdetails/PassengerDetailsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/util/KarhooErrorUtil.kt, uisdk/src/main/res/layout/uisdk_booking_request.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt
[MOB-3350](https://karhoo.atlassian.net/browse/MOB-3350)
=> Mob 3350 part 2

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/KarhooUISDKConfiguration.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestViewContract.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/bookingrequest/BookingRequestPresenterTest.kt
… the API
[MOB-3372](https://karhoo.atlassian.net/browse/MOB-3372)
=> Add BookingMeta to Booking Activity builder parameters and send it to the API

uisdk/build.gradle
[MOB-3173](https://karhoo.atlassian.net/browse/MOB-3173)
=> [MOB-3173] Fix tracking links

uisdk/src/main/java/com/karhoo/uisdk/screen/address/map/AddressMapMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/map/AddressMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/map/AddressMapView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/address/map/AddressMapPresenterTest.kt
[MOB-3240](https://karhoo.atlassian.net/browse/MOB-3240)
=> Mob 3240 soul buoy

uisdk/src/main/java/com/karhoo/uisdk/KarhooUISDKConfiguration.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt
[MOB-3350](https://karhoo.atlassian.net/browse/MOB-3350)
=> added check to see if user or not

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/KarhooEnvironmentExt.kt, uisdk/src/main/res/values/strings.xml
[MOB-3173](https://karhoo.atlassian.net/browse/MOB-3173)
Use extensions and string resources for guest trip tracking URL
=> Use extensions and string resources for guest trip tracking URL

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/passengerdetails/PassengerDetailsView.kt
[MOB-3350](https://karhoo.atlassian.net/browse/MOB-3350)
=> small logic change

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt
[MOB-3350](https://karhoo.atlassian.net/browse/MOB-3350)
=> removed unused method

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt
[MOB-3311](https://karhoo.atlassian.net/browse/MOB-3311)
Fixed issue with pickup icon not becoming visible when deleting the destination address
=> Fixed issue with pickup icon not becoming visible when deleting the destination address

uisdk/src/main/res/layout/uisdk_activity_booking_main.xml
=> [MOB-XXXX] Make side menu icons changeable

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesSortView.kt, uisdk/src/main/res/drawable/uisdk_ic_sort_left_disabled.xml
[MOB-3298](https://karhoo.atlassian.net/browse/MOB-3298)
=> When prebooking do not disable ETA sorting button, but remove sorting controls entirely.

uisdk/src/main/res/layout/uisdk_view_address_map.xml
[MOB-3311](https://karhoo.atlassian.net/browse/MOB-3311)
=> Apply white color to fab button

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/quotes/BookingQuotesMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/quotes/BookingQuotesPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/quotes/BookingQuotesView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListItemView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/util/DateUtil.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/ServiceCancellationExt.kt, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/quotes/BookingQuotesPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/util/ServiceCancellationExtTests.kt
[MOB-3376](https://karhoo.atlassian.net/browse/MOB-3766)
Created this for early review, still fixing the Unit test failures. 
=> [MOB-3376] Cancellation SLA text

uisdk/src/test/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenterTest.kt
[MOB-3376](https://karhoo.atlassian.net/browse/MOB-3376)
=> [MOB-3376] Fix circle ci failing tests

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenterTest.kt
[MOB-3388](https://karhoo.atlassian.net/browse/MOB-3388)
=> UI SDK Release 1.4.0 (develop)

build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/braintree/BraintreePaymentPresenter.kt
[MOB-3418](https://karhoo.atlassian.net/browse/MOB-3418)
=> [MOB-3418] Fix GBP bug with EUR quotes.

README.md, uisdk/README.md, uisdk/build.gradle
[MOB-3433](https://karhoo.atlassian.net/browse/MOB-3433)
=> MOB-3433 Release 1.4.1

README.md, build.gradle, uisdk/README.md, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/TimePickerTitleView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/bookingrequest/BookingRequestView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/payment/braintree/BraintreePaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesSortView.kt, uisdk/src/main/res/drawable/uisdk_booking_button_background.xml, uisdk/src/main/res/drawable/uisdk_gradient_disabled.xml, uisdk/src/main/res/drawable/uisdk_gradient_enabled.xml, uisdk/src/main/res/layout/uisdk_activity_address.xml, uisdk/src/main/res/layout/uisdk_activity_feedback.xml, uisdk/src/main/res/layout/uisdk_activity_ride_detail.xml, uisdk/src/main/res/layout/uisdk_activity_rides.xml, uisdk/src/main/res/layout/uisdk_view_address_map.xml, uisdk/src/main/res/layout/uisdk_view_booking_button.xml, uisdk/src/main/res/layout/uisdk_view_booking_map.xml, uisdk/src/main/res/values/colors.xml, uisdk/src/main/res/values/styles.xml
[MOB-3433](https://karhoo.atlassian.net/browse/MOB-3433)
=> MOB-3433 Post Release 1.4.1

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/web/KarhooWebView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/web/WebActivity.kt
[MOB-3255](https://karhoo.atlassian.net/browse/MOB-3255)
=> Mob 3255 target from 29 to 30

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/BookingTermsView.kt, uisdk/src/main/res/layout/uisdk_view_booking_terms.xml, uisdk/src/main/res/values/styles.xml
[MOB-3403](https://karhoo.atlassian.net/browse/MOB-3403)
Fixed terms and conditions styling
=> MOB-3403 Fixed terms and conditions styling

uisdk/src/main/java/com/karhoo/uisdk/screen/web/WebActivity.kt
[MOB-3421](https://karhoo.atlassian.net/browse/MOB-3421)
=> Fix scrolling issue on the web view

uisdk/build.gradle
[MOB-3447](https://karhoo.atlassian.net/browse/MOB-3447)
=> MOB-3447 use network sdk 1 4 1

uisdk/build.gradle
[MOB-3447](https://karhoo.atlassian.net/browse/MOB-3447)
=> MOB-3447 Release 1.4.2

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/notification/rides/past/RideNotificationView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/BookingTermsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListItemView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/past/card/PastRideCardView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/driverphoto/DriverPhotoActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/tripinfo/TripInfoView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/web/KarhooWebView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/web/WebActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/util/PicassoLoader.kt, uisdk/src/main/res/layout/uisdk_view_booking_terms.xml, uisdk/src/main/res/values/styles.xml
[MOB-3447](https://karhoo.atlassian.net/browse/MOB-3447)
=> MOB-3447 Final Release 1.4.2

README.md
[MOB-3447](https://karhoo.atlassian.net/browse/MOB-3447)
=> readme ui sdk to 1_4_2

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt
[MOB-3409](https://karhoo.atlassian.net/browse/MOB-3409)
=> [MOB-3409] hide locate me button when quotes appear

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/TripActivity.kt
[MOB-3487](https://karhoo.atlassian.net/browse/MOB-3487)
=> MOB-3487 Add option to Trip activity to close or open booking screen

uisdk/src/main/java/com/karhoo/uisdk/screen/address/options/AddressOptionsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/rating/RatingView.kt
[MOB-3469](https://karhoo.atlassian.net/browse/MOB-3469)
=> Keep RatingView gone.

README.md, uisdk/README.md, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/address/options/AddressOptionsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/booking/tripallocation/TripAllocationView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/rating/RatingView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/TripActivity.kt
[MOB-3489](https://karhoo.atlassian.net/browse/MOB-3489)
=> MOB-3489 Release 1.4.3 (master)

README.md, uisdk/README.md, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/address/options/AddressOptionsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/tripallocation/TripAllocationView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/rating/RatingView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/TripActivity.kt
[MOB-3489](https://karhoo.atlassian.net/browse/MOB-3489)
=> MOB-3489 Release 1.4.3 (develop)

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentView.kt, uisdk/src/main/res/layout/uisdk_view_booking_checkout_payment.xml, uisdk/src/main/res/layout/uisdk_view_booking_comments.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/styles.xml
[MOB-3392](https://karhoo.atlassian.net/browse/MOB-3392)
=> Mob 3392 component UI and behaviour fixes

uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml
[MOB-3507](https://karhoo.atlassian.net/browse/MOB-3507)
Very quick and small PR for translations
=> [MOB-3507] Quote Translations

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/CheckoutActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragmentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/tripallocation/TripAllocationView.kt, uisdk/src/main/res/layout/uisdk_view_booking_quotes.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-3427](https://karhoo.atlassian.net/browse/MOB-3427)
MOB-3427  [Payment] As a user I can book when the credit card and passenger details are completed
=> MOB-3427  [Payment] As a user I can book when the credit card and passenger details are completed

README.md, uisdk/README.md, uisdk/build.gradle
[MOB-3513](https://karhoo.atlassian.net/browse/MOB-3513)
Update Adyen SDK to 3.8.3
=> MOB-3513 Release 1 4 4

README.md, uisdk/README.md, uisdk/build.gradle
[MOB-3513](https://karhoo.atlassian.net/browse/MOB-3513)
=> MOB-3513 Release 1.4.4 (Develop)

uisdk/src/main/java/com/karhoo/uisdk/screen/address/addresslist/AddressResultListView.kt
[MOB-3504](https://karhoo.atlassian.net/browse/MOB-3504)
=> MOB 3504 fix

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt
[MOB-3455](https://karhoo.atlassian.net/browse/MOB-3455)
=> MOB 3455 try catch for a callback issue

uisdk/src/main/java/com/karhoo/uisdk/base/view/countrycodes/CountryPickerActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/res/layout/uisdk_activity_country_picker.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values/colors.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/main/res/values/styles.xml
[MOB-3419](https://karhoo.atlassian.net/browse/MOB-3419)
MOB-3419 Added a toolbar in the country picker activity
=> MOB-3419 Added a toolbar in the country picker activity

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-3525](https://karhoo.atlassian.net/browse/MOB-3525)
MOB-3525 [Quote Summary] Handle errors
=> MOB-3525 [Quote Summary] Handle errors

uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml
[MOB-3407](https://karhoo.atlassian.net/browse/MOB-3407)
=> [MOB-3407] Track driver translation change

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-3529](https://karhoo.atlassian.net/browse/MOB-3529)
=> [MOB-3529] Send flight number with nonce for bookings

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt
[MOB-3529](https://karhoo.atlassian.net/browse/MOB-3529)
=> [MOB-3529] Remove flight details

uisdk/src/main/res/layout/uisdk_view_contact_options.xml, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/layout/uisdk_view_upcoming_ride_card.xml
[MOB-3569](https://karhoo.atlassian.net/browse/MOB-3569)
MOB-3569 Change the buttons position on rides booked list
=> MOB-3569 Change the buttons position on rides booked list

uisdk/src/main/res/values/styles.xml
[MOB-3458](https://karhoo.atlassian.net/browse/MOB-3458)
=> [MOB-3458] Override Adyen button color

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/util/KarhooErrorUtil.kt, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3497](https://karhoo.atlassian.net/browse/MOB-3497)
=> [MOB-3497] New API error codes

uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3626](https://karhoo.atlassian.net/browse/MOB-3626)
MOB-3626 Download and upload strings on phrase.com
=> MOB-3626 Download and upload strings on phrase.com

uisdk/src/main/res/layout/uisdk_view_contact_options.xml, uisdk/src/main/res/layout/uisdk_view_error_state.xml, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/layout/uisdk_view_trip_info.xml, uisdk/src/main/res/layout/uisdk_view_upcoming_ride_card.xml
[MOB-3569](https://karhoo.atlassian.net/browse/MOB-3569)
MOB-3569 Change the buttons position on rides booked list
=> MOB-3569 Improved spacing between buttons

uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml
[MOB-3626](https://karhoo.atlassian.net/browse/MOB-3626)
MOB-3626-2 Added latest translations
=> MOB-3626-2 Added latest translations

README.md, uisdk/README.md, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt
MOB-3631 Android UI SDK Release 1.5.0
=> MOB-3631 Android UI SDK Release 1.5.0

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/BookingTermsView.kt
=> Fix Karhoo Privacy policy URL

uisdk/build.gradle
=> MOB-3631: Release 1.5.0 (develop) [2nd]

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/BookingTermsView.kt, uisdk/src/main/res/drawable/uisdk_gradient_disabled.xml
=> MOB-3631: Post release 1.5.0 [master] [2nd]

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/category/CategorySelectorView.kt
=> MOB-3631: Hot fixes for payer id and category name

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/category/CategorySelectorView.kt
=> Mob 3631: Post Release 1.5.0 [3rd]

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenter.kt
=> MOB-3631: Hotfix for Release 1.5.0 (develop)

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenter.kt
=> MOB-3631: Hotfix Post Release 1.5.0 [master] fourth

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/CheckoutActivity.kt
[MOB-3572](https://karhoo.atlassian.net/browse/MOB-3572)
I've cleared the reference to CheckoutFragment from the recreation of CheckoutActivity's bundle.
- [ x] Bugfix 
=> MOB-3572_Passenger-details-page-breaks-on-some-cases

uisdk/src/main/java/com/karhoo/uisdk/base/CollapsiblePanelView.java, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt, uisdk/src/main/res/layout/uisdk_activity_booking_content.xml, uisdk/src/main/res/layout/uisdk_view_quotes_recycler.xml, uisdk/src/main/res/values/attrs.xml, uisdk/src/main/res/values/integers.xml
[MOB-3659](https://karhoo.atlassian.net/browse/MOB-XXXX)
Increase list height when maximized with a match_parent and added a percentage of the screen to be used by QuotesListView.
- [ x] Bugfix 
=> MOB-3659 Increase list height when maximized

uisdk/src/main/java/com/karhoo/uisdk/screen/trip/map/TripMapPresenter.kt
[MOB-3602](https://karhoo.atlassian.net/browse/MOB-3602)
Added the check whether we don't have tripdetails yet, but a driver and zoomed on it.
=> Android Track driver map zoom is too big

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentView.kt
[MOB-3531](https://karhoo.atlassian.net/browse/MOB-3531)
Whenever the card selection is cancelled without selecting a card we now check and show again the Add Payment label.
=> Android Payment card subtitle dissapearing

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/BookingTermsView.kt, uisdk/src/main/res/drawable/uisdk_background_eta_price_view_rounded.xml, uisdk/src/main/res/layout/uisdk_view_booking_comments.xml, uisdk/src/main/res/layout/uisdk_view_booking_passenger_details.xml, uisdk/src/main/res/values/styles.xml
[MOB-3400](https://karhoo.atlassian.net/browse/MOB-3400)
Changed colors according Olivier and Matt
=> MOB-3400  [Branding] As a DP developer, I can customize all pages easily because I have guidelines and indicative palette

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/category/CategorySelectorView.kt
[MOB-3690](https://karhoo.atlassian.net/browse/MOB-3690)
Added a check for different categories as seems that when the reservation is in the future, the tablayout is not recreated but categories may come in another order 
=> Quote filters by Vehicle category are not filtering correctly

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsView.kt
[MOB-3683](https://karhoo.atlassian.net/browse/MOB-3683)
Called the validation callback once more after the fields are validated.
=> MOB-3683  NEXT button should be enabled when passenger details are partially missing

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/PaymentDropInContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/LocaleExt.kt
[MOB-3696](https://karhoo.atlassian.net/browse/MOB-3696)
Added context and locale on uisdk. The nsdk already had what needed.
=> MOB-3696  [Payment] Change the locale on Adyen PSP to have "credit card" translated

uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3700](https://karhoo.atlassian.net/browse/MOB-3700)
=> [MOB-3700] Adyen pay button change to Pre-Authorize

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsView.kt
[MOB-3707](https://karhoo.atlassian.net/browse/MOB-3707)
Requested focus on mobile when country picker ends
=> MOB-3707  Focus on the phone number field after phone prefix is selected

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/LocaleExt.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailabilityTest.kt
[MOB-3688](https://karhoo.atlassian.net/browse/MOB-3688)
Added locale to quotes retrieval
=> MOB-3688  Add locale parameter to Retrieve Quote List endpoint

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/CheckoutActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragmentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/quotes/BookingQuotesViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/quotes/BookingQuotesViewModel.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3647](https://karhoo.atlassian.net/browse/MOB-3647)
[Booking] As a user, I'm warned when a quote has expired
=> MOB-3647 [Booking] As a user, I'm warned when a quote has expired

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/CheckoutActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragmentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/quotes/BookingQuotesViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/quotes/BookingQuotesViewModel.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3686](https://karhoo.atlassian.net/browse/MOB-3686)
[UI SDK] As Karhoo, I want to send the loyalty nonce in order to validate the transaction
=> MOB-3686 [UI SDK] As Karhoo, I want to send the loyalty nonce in order to validate the transaction

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentView.kt, uisdk/src/main/res/layout/uisdk_view_booking_payment.xml
[MOB-3508](https://karhoo.atlassian.net/browse/MOB-3508)
MOB-3508 Checkout component UI review Android
=> MOB-3508 Checkout component UI review Android

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyPresenter.kt
[MOB-3686](https://karhoo.atlassian.net/browse/MOB-3686)
MOB-3686 Fixed flexpay issue
=> MOB-3686 Fixed flexpay issue

uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3803](https://karhoo.atlassian.net/browse/MOB-3803)
There were no strings different so I copied the Prhase.com strings file to our project.
=> MOB-3803  [Loyalty] Synchronize the translation in the 6 languages from phrase.com before release

uisdk/src/main/res/layout/uisdk_activity_rides.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3794](https://karhoo.atlassian.net/browse/MOB-3794)
Added a new string on Phrase and set to the button on RidesList
=> MOB-3794  Use two different button wording on Checkout and Rides list

uisdk/src/main/res/layout/uisdk_view_address_picker.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3768](https://karhoo.atlassian.net/browse/MOB-3768)
Added strings on Phrase and content description for the two icons
=> MOB-3768  [Accessibility] Improvements on Address component for Android

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/util/KarhooErrorUtil.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyViewPresenterTest.kt
[MOB-3756](https://karhoo.atlassian.net/browse/MOB-3756)
=> MOB-3756 Add Slug tag to the KarhooError

uisdk/README.md, uisdk/build.gradle
[MOB-3748](https://karhoo.atlassian.net/browse/MOB-3748)
Android Network SDK Release v1.4.4/ UI SDK1.5.1
=> MOB-3748: Release 1.5.1 [develop]

uisdk/README.md, uisdk/build.gradle, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml
[MOB-3748](https://karhoo.atlassian.net/browse/MOB-3748)
Release 1.5.1
=> MOB-3748 release 1.5.1

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyView.kt, uisdk/src/main/res/drawable/uisdk_loyalty_balance_background.xml, uisdk/src/main/res/drawable/uisdk_loyalty_balance_error_background.xml, uisdk/src/main/res/layout/uisdk_view_loyalty_view.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/colors.xml, uisdk/src/main/res/values/dimens.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/main/res/values/styles.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyViewPresenterTest.kt
[MOB-3784](https://karhoo.atlassian.net/browse/MOB-3784)
Added Loyalty Balance tag
=> Mob 3784 loyalty display the balance in the loyalty component

uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml
[MOB-3823](https://karhoo.atlassian.net/browse/MOB-3823)
Added strings.xml (fr-rFR) -> r from Region
=> MOB-3823  Change "Pay" wording by "pre-authorise" in Adyen Drop-in

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/BookingTermsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/legalnotice/LegalNoticeContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/legalnotice/LegalNoticePresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/legalnotice/LegalNoticeView.kt, uisdk/src/main/res/layout/uisdk_booking_checkout_view.xml, uisdk/src/main/res/layout/uisdk_view_legal_notice.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/main/res/values/styles.xml
[MOB-3845](https://karhoo.atlassian.net/browse/MOB-3845)
Add "Legal Notice" placeholder under T&C on the Checkout page
=> MOB-3845 Add "Legal Notice" placeholder under T&C on the Checkout page

uisdk/src/main/java/com/karhoo/uisdk/analytics/Analytics.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/adapter/AddressAdapter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/addresslist/AddressResultListView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/domain/KarhooAddressProvider.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/rating/RatingView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/feedback/FeedbackPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/map/TripMapPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/address/domain/KarhooAddressProviderTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailabilityTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/feedback/FeedbackPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/trip/map/TripMapPresenterTest.kt
[MOB-3861](https://karhoo.atlassian.net/browse/MOB-3861)
Marked as deprecated all the unused or not so used analytics.
=> MOB-3861 Clean the outdated analytics events in the UI SDK

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/legalnotice/LegalNoticeView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/support/KarhooFeedbackEmailComposer.kt
[MOB-3845](https://karhoo.atlassian.net/browse/MOB-3845)
MOB-3845  Added additional info in the email footer
=> MOB-3845-2 Added additional info in the email footer

uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt
[MOB-3882](https://karhoo.atlassian.net/browse/MOB-3882)
Fix for UI Tests. Disabling Checkout component tests
=> MOB-3882_fix_uitests_build

uisdk/src/main/res/drawable/kh_ic_check_selected.xml, uisdk/src/main/res/drawable/uisdk_ic_pickup.xml, uisdk/src/main/res/drawable/uisdk_ic_sort_left_selected.xml, uisdk/src/main/res/drawable/uisdk_ic_sort_right_selected.xml, uisdk/src/main/res/layout/uisdk_activity_rides.xml, uisdk/src/main/res/layout/uisdk_view_address_search.xml, uisdk/src/main/res/values/colors.xml, uisdk/src/main/res/values/styles.xml
[MOB-3851](https://karhoo.atlassian.net/browse/MOB-3851)
Modified colors accordingly
=> MOB-3851 Matt's Styleguide feedbacks

uisdk/src/main/java/com/karhoo/uisdk/analytics/Analytics.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesListView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/RidesActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/TripActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/bookingstatus/contact/ContactOptionsPresenter.kt
[MOB-3868](https://karhoo.atlassian.net/browse/MOB-3868)
Added missing Analytics
=> MOB-3868 Add basic analytics events to track the conversion steps

uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3729](https://karhoo.atlassian.net/browse/MOB-3729)
Updated translation files
=> MOB-3729 [Release #10] Update the translations

app/src/main/java/com/karhoo/samples/uisdk/dropin/config/AdyenTokenExchangeConfig.kt, uisdk/src/main/java/com/karhoo/uisdk/KarhooUISDKConfiguration.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragmentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/BookingTermsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/res/anim/uisdk_shake_control.xml, uisdk/src/main/res/anim/uisdk_shake_cycle.xml, uisdk/src/main/res/layout/uisdk_view_booking_terms.xml, uisdk/src/main/res/values/styles.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-3881](https://karhoo.atlassian.net/browse/MOB-3881)
Added checkbox for terms and conditions based on configuration
=> MOB-3881 As Karhoo, I want the user to check a checkbox related to legal statements before booking

uisdk/README.md, uisdk/build.gradle
[MOB-3892](https://karhoo.atlassian.net/browse/MOB-3892)
Pre release of version 1.5.2
=> MOB-3892: Release 1.5.2 [develop]

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarView.kt
[MOB-3808](https://karhoo.atlassian.net/browse/MOB-3808)
Changed visibility for image and divider to GONE
=> MOB-3808 Address Component: Move the x cross to the right of the destination

uisdk/src/androidTest/java/com/karhoo/uisdk/booking/GuestBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/adyen/AdyenBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/BaseRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt
=> Fixed and refactor all test classes

uisdk/src/main/res/drawable/uisdk_ic_add_destination.xml
[MOB-3933](https://karhoo.atlassian.net/browse/MOB-3933)
Changed to secondary color the plus on the add destination
=> Fix Add Destination Icon Color

uisdk/src/main/res/layout/uisdk_view_address_search.xml
[MOB-3771](https://karhoo.atlassian.net/browse/MOB-3771)
Added Content Description for TalkBack
=> MOB-3771 [Accessibility] Improvements on Address Search for Android

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerPresenterTest.kt
=> Update TimeDatePickerPresenter with the new JourneyDetails naming

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt
[MOB-1307](https://karhoo.atlassian.net/browse/MOB-1307)
Raised the cleanup event for journeyDetails
=> MOB-1307 Behaviour difference between iOS & Android: Cancelling on allocation

uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml
[MOB-3956](https://karhoo.atlassian.net/browse/MOB-3956)
=> Update FR AND NL translations

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenPaymentPresenter.kt
[MOB-3972](https://karhoo.atlassian.net/browse/MOB-3972)](https://karhoo.atlassian.net/browse/MOB-3972)
=> MOB-3972: Remove Save My Credit Card on Adyen

uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
Exported the most recent locale files from Phrase
=> Updated translations from Phrase

.phrase.yml, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/QuoteVehicleExt.kt, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3627](https://karhoo.atlassian.net/browse/MOB-3627)
Added vehicle type to checkout screen to replace the old vehicle class.
=> [MOB-3627] Vehicle Type on Checkout

README.md, uisdk/README.md, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/prebookconfirmation/PrebookConfirmationView.kt, uisdk/src/main/res/layout/uisdk_booking_checkout_activity.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml
[MOB-3968](https://karhoo.atlassian.net/browse/MOB-3968)
=> MOB-3968: Release 1.5.3 [master]

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragmentPresenter.kt, uisdk/src/main/res/layout/uisdk_view_quotes_recycler.xml
[MOB-3997](https://karhoo.atlassian.net/browse/MOB-3997)
MOB-3997 Hide sorting/filter widgets when the quote list is loading
=> MOB-3997 Hide sorting/filter widgets when the quote list is loading

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt
Cancelled the availability provider when left the quotes fragment
=> Cancelled the availability provider when left the quotes fragment

uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml
[MOB-4005](https://karhoo.atlassian.net/browse/MOB-4005)
=> Mob 4005 add track driver option in ride details screen

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/BookingTermsView.kt
=> hideKeyboardWhenTCClicked

uisdk/src/main/java/com/karhoo/uisdk/screen/rides/past/PastRidesPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/UpcomingRidesPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/past/PastRidesPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/rides/upcoming/UpcomingRidesPresenterTest.kt
[MOB-4042](https://karhoo.atlassian.net/browse/MOB-4042)
Default 10 items per page
=> Mob 4042 past rides error ksdk05 not showing up any rides

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesAdapter.java, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesSortView.kt
[MOB-4046](https://karhoo.atlassian.net/browse/MOB-4046)
=> MOB-4046 Default sort on price for ASAP

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenPaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenPaymentView.kt
[MOB-4025](https://karhoo.atlassian.net/browse/MOB-4025)
=> Rekease 1.5.4-rc2

README.md, uisdk/README.md, uisdk/build.gradle
[MOB-4025](https://karhoo.atlassian.net/browse/MOB-4025)
Release 1.5.5
=> MOB-4025 release 1.5.5

README.md, uisdk/README.md, uisdk/build.gradle, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4025](https://karhoo.atlassian.net/browse/MOB-4025)
Release 1.5.6 
=> Release 1.5.6

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/PriceSort.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesListItemView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/QuoteVehicleExt.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailabilityTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/domain/quotes/PriceSortTest.kt
[MOB-4011](https://karhoo.atlassian.net/browse/MOB-4011)
Removed vehicle.class from quotes list
=> MOB-4011  Remove vehicle.class from Quote card on Android

uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/GuestBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/adyen/AdyenBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/braintree/BraintreeBookingTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/trip/TripTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/main/res/layout/uisdk_view_booking_quotes.xml, uisdk/src/main/res/layout/uisdk_view_quotes_list.xml, uisdk/src/main/res/layout/uisdk_view_trip_info.xml
[MOB-4122](https://karhoo.atlassian.net/browse/MOB-4122)
[Updated all failing tests and changed tests to suit new quote list page]
=> Updated tests for quote list

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt
[MOB-4048](https://karhoo.atlassian.net/browse/MOB-4048)
=> MOB-4048 Use the passenger and luggage in booking request

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/CheckoutActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/tripallocation/TripAllocationView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt
[MOB-4113](https://karhoo.atlassian.net/browse/MOB-4113)
=> [Accor-34]Proper fix for Accor about background crash (preserve background activity)

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt
[MOB-4105](https://karhoo.atlassian.net/browse/MOB-4105)
MOB-4105 Add missing payment managers from the develop branch
=> MOB-4105 Add missing payment managers from the develop branch

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt
[MOB-4141](https://karhoo.atlassian.net/browse/MOB-4141)
=> MOB-4141 remove refs

README.md, uisdk/README.md, uisdk/build.gradle, uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentPresenter.kt, uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentView.kt
Fix issue with production env for Adyen payment provider
Fix issue with production env for Adyen payment provider
=> Fix issue with production env for Adyen payment provider

uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenPaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenterTest.kt
[MOB-4157](https://karhoo.atlassian.net/browse/MOB-4157)
=> MOB-4157   Refine unit test for payment flow on UI SDK

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/CheckoutActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt
[MOB-4018](https://karhoo.atlassian.net/browse/MOB-4018)
MOB-4018 Layout table view without being in the view hierarchy
=> MOB-4018 Layout table view without being in the view hierarchy

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/quotes/BookingQuotesMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/quotes/BookingQuotesView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/capacity/CapacityMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/capacity/CapacityView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/extendedcapabilities/CapabilityAdapter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/LuggageFilter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/PassengersFilter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/quotes/mocks/BookingQuotesViewMock.kt
[MOB-4044](https://karhoo.atlassian.net/browse/MOB-4044)
=> Mob 4044 luggage/passengers display 0 or don't display depending on api response

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/AvailabilityProvider.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt, uisdk/src/main/res/layout/uisdk_quotes_activity.xml, uisdk/src/main/res/layout/uisdk_view_quotes_error.xml, uisdk/src/main/res/layout/uisdk_view_quotes_list.xml, uisdk/src/main/res/layout/uisdk_view_quotes_recycler.xml
[MOB-4194](https://karhoo.atlassian.net/browse/MOB-4194)
=> MOB-4194   [Quote] Address components and filters should not be visible while scrolling quote list

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/MultiSelectChipsFilterView.kt, uisdk/src/main/res/layout/uisdk_view_filter.xml, uisdk/src/main/res/layout/uisdk_view_filter_multi_select_chips.xml, uisdk/src/main/res/layout/uisdk_view_quotes_item.xml, uisdk/src/main/res/layout/uisdk_view_quotes_recycler.xml, uisdk/src/main/res/values/styles.xml
[MOB-4190](https://karhoo.atlassian.net/browse/MOB-4190)
=> MOB-4190  [Quote] Android quote list v1 feedbacks (layout)

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4195](https://karhoo.atlassian.net/browse/MOB-4195)
=> Mob 4195 quote show number of results on the navigation bar

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/NumberedFilterView.kt
[MOB-4215](https://karhoo.atlassian.net/browse/MOB-4215)
=> MOB-4215   [Filter page] Luggage '- button' wrong colour

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesRecyclerView.kt
[MOB-4206](https://karhoo.atlassian.net/browse/MOB-4206)
=> MOB-4206   Filter and Sort by buttons no longer visible after returning from checkout page

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesListItemView.kt
[MOB-4248](https://karhoo.atlassian.net/browse/MOB-4248)
show luxury and executive on quote cell
=> MOB 4248 show luxury and executive on quote cell

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt
[MOB-4276](https://karhoo.atlassian.net/browse/MOB-4276)
=> MOB-4276   [Quote] Destination should remain empty on ride planning

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/errorview/QuotesErrorView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/errorview/QuotesErrorViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/errorview/QuotesErrorViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesRecyclerView.kt, uisdk/src/main/res/values/strings.xml
[MOB-4273](https://karhoo.atlassian.net/browse/MOB-4273)
App crash when airplane mode is on
=> MOB-4273 App crash when airplane mode is on

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/domain/quotes/KarhooAvailability.kt
[MOB-4275](https://karhoo.atlassian.net/browse/MOB-4275)
MOB-4275 Fix issue with quotes being hidden after complete status
=> MOB-4275 Fix issue with quotes being hidden after complete status

uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentPresenter.kt, uisdk/src/braintree/java/BraintreePaymentPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/analytics/Analytics.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt
[MOB-4222](https://karhoo.atlassian.net/browse/MOB-4222)
=> MOB-4222  Align analytics Keys (in UI and Network SDK) between platforms

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt
[MOB-4221](https://karhoo.atlassian.net/browse/MOB-4221)
MOB-4221 Removed main activity payment providers
=> MOB-4221 Removed main activity payment providers

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/CheckoutActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesRecyclerContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesRecyclerView.kt, uisdk/src/main/res/layout/uisdk_booking_checkout_activity.xml, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4316](https://karhoo.atlassian.net/browse/MOB-4316)
[MOB-4315](https://karhoo.atlassian.net/browse/MOB-4315)
=> Mob 4316 & Mob 4315 wrong text for no asap availability

app/build.gradle, uisdk/build.gradle
[MOB-4264](https://karhoo.atlassian.net/browse/MOB-4264)
=> MOB-4264  [UI SDK] Target Android API 31

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/RidesActivity.kt
[MOB-4137](https://karhoo.atlassian.net/browse/MOB-4137)
=> Mob 4137 passenger mobile phone lost when the user clicks on new ride from rides list

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/FilterDialogFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/VehicleEcoFilter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/VehicleTypeFilter.kt
[MOB-4325](https://karhoo.atlassian.net/browse/MOB-4325)
=> [Filter] Filtering is not correct in other languages than EN

uisdk/README.md, uisdk/build.gradle
[MOB-4321](https://karhoo.atlassian.net/browse/MOB-4321)
=> Release 1.7.1

uisdk/README.md, uisdk/build.gradle, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4321](https://karhoo.atlassian.net/browse/MOB-4321)
=> Release 1.7.2

uisdk/README.md, uisdk/build.gradle, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4321](https://karhoo.atlassian.net/browse/MOB-4321)
=> Mob 4321 post release 1 7 2

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/filterview/VehicleClassFilter.kt
[MOB-4321](https://karhoo.atlassian.net/browse/MOB-4321)
=> Mob 4321 release 1 7 2 2

uisdk/build.gradle, uisdk/src/adyen/build.gradle, uisdk/src/braintree/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesActivity.kt, uisdk/src/main/res/layout/uisdk_quotes_activity.xml
[MOB-4345](https://karhoo.atlassian.net/browse/MOB-4345)
=> Display issues when app was in background

uisdk/README.md, uisdk/build.gradle
=> Release 1.7.3

uisdk/README.md, uisdk/build.gradle, uisdk/src/adyen/build.gradle, uisdk/src/braintree/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/QuotesActivity.kt, uisdk/src/main/res/layout/uisdk_quotes_activity.xml
=> Post release 1 7 3

uisdk/README.md, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragmentPresenter.kt
=> Post release 1 7 3 

uisdk/build.gradle
[MOB-4125](https://karhoo.atlassian.net/browse/MOB-4125)
Bump SDK version
=> MOB-4125 Bump SDK version

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, uisdk/build.gradle
[MOB-4125](https://karhoo.atlassian.net/browse/MOB-4125)
=> MOB-4125 Fix callbacks not invoked and remove logout call

README.md, uisdk/README.md
[MOB-4361](https://karhoo.atlassian.net/browse/MOB-4361)
=> MOB-4361 Update readme to latest versions

uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentPresenter.kt, uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentView.kt, uisdk/src/braintree/java/BraintreePaymentPresenter.kt, uisdk/src/braintree/java/BraintreePaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragmentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BookingPaymentView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/PaymentDropInContract.kt
[MOB-4146](https://karhoo.atlassian.net/browse/MOB-4146)
=> Spike automating the booking request after 3DS step to determine if it is possible to simplify our checkout journey after Adyen SDK upgrade

app/build.gradle, build.gradle, uisdk/build.gradle, uisdk/src/adyen/build.gradle, uisdk/src/androidTest/AndroidManifest.xml, uisdk/src/androidTest/java/com/karhoo/uisdk/address/screenshot/AddressScreenshotTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/BaseRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/PreferencesRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ScreenshotTest.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ServerRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/testrunner/UiSDKTestRunner.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/quotes/screenshot/QuotesRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/quotes/screenshot/QuotesScreenshotTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestSDKConfig.kt, uisdk/src/braintree/build.gradle, uisdk/src/main/res/layout/uisdk_view_filter.xml, uisdk/src/main/res/layout/uisdk_view_quotes_sort.xml
[MOB-4411](https://karhoo.atlassian.net/browse/MOB-4411)
=> MOB-4411 Implement 3rd party for snapshot testing

uisdk/src/braintree/java/BraintreePaymentPresenter.kt, uisdk/src/main/res/drawable/kh_uisdk_ic_passenger.xml, uisdk/src/main/res/layout/uisdk_action_cell_view.xml, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/dimens.xml, uisdk/src/main/res/values/strings.xml
[MOB-4330](https://karhoo.atlassian.net/browse/MOB-4330)
=> Changed passenger icon and size

uisdk/src/androidTest/java/com/karhoo/uisdk/common/BaseRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/quotes/screenshot/QuotesRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/quotes/screenshot/QuotesScreenshotTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt
[MOB-4398](https://karhoo.atlassian.net/browse/MOB-4398)
=> MOB-4398 Add quote list snapshot tests

uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/presenter/CheckoutPresenterTests.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-4453](https://karhoo.atlassian.net/browse/MOB-4453)
=> Update payment related tests after 1-step payment implementation

uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4459](https://karhoo.atlassian.net/browse/MOB-4459)
=> Authorisation wording in Loyalty Burn mode

uisdk/src/androidTest/java/com/karhoo/uisdk/common/BaseRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/quotes/screenshot/QuotesRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/quotes/screenshot/QuotesScreenshotTests.kt
[MOB-4415](https://karhoo.atlassian.net/browse/MOB-4415)
MOB-4442 Fixed compatibility issues with various machines in regard to scrolling the quotes/filters list
=> MOB-4442 Fixed compatibility issues with various machines in regard to scrolling the quotes/filters list

uisdk/build.gradle, uisdk/src/adyen/build.gradle
[MOB-4465](https://karhoo.atlassian.net/browse/MOB-4465)
=> Upgrade Adyen SDK in order to fix payment issues on Android 13

uisdk/src/main/java/com/karhoo/uisdk/util/KarhooErrorUtil.kt, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3664](https://karhoo.atlassian.net/browse/MOB-3664)
=> Small fix payment codes

uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-3665](https://karhoo.atlassian.net/browse/MOB-3665)
=> MOB-3665 fix more keys

uisdk/build.gradle, uisdk/src/androidTest/java/com/karhoo/uisdk/AndroidManifest.xml, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/BookingRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/checkout/bookingconfirmation/BookingConfirmationRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/booking/checkout/bookingconfirmation/BookingConfirmationScreenshotTests.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/BaseRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ScreenshotTest.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/common/ServerRobot.kt, uisdk/src/androidTest/java/com/karhoo/uisdk/util/TestData.kt, uisdk/src/debug/AndroidManifest.xml, uisdk/src/debug/java/MockBookingConfirmationBaseActivity.kt, uisdk/src/debug/res/layout/uisdk_mock_booking_confirmation_layout.xml
[MOB-4487](https://karhoo.atlassian.net/browse/MOB-4487)
MOB-4487 [Booking Confirmation] Screenshot testing
=> MOB-4487 [Booking Confirmation] Screenshot testing

app/src/main/java/com/karhoo/samples/uisdk/dropin/KarhooAnalytics.kt, uisdk/src/main/java/com/karhoo/uisdk/analytics/Analytics.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/bookingconfirmation/BookingConfirmationView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt
[MOB-4455](https://karhoo.atlassian.net/browse/MOB-4455)
=> [Booking Confirmation] Add analytics events

app/build.gradle, app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, settings.gradle, uisdk/build.gradle, uisdk/src/main/AndroidManifest.xml, uisdk/src/main/res/layout/uisdk_quotes_fragment.xml, uisdk/src/main/res/values/dimens.xml, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-4510](https://karhoo.atlassian.net/browse/MOB-4510)
=> Braintree removal

uisdk/src/debug/java/MockBookingConfirmationBaseActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/bookingconfirmation/BookingConfirmationView.kt
[MOB-4489](https://karhoo.atlassian.net/browse/MOB-4489)
=> Fixed tests & bottom sheet expanded

uisdk/src/adyen/res/values/styles.xml, uisdk/src/braintree/res/values/styles.xml, uisdk/src/main/java/com/karhoo/uisdk/screen/address/static/AddressStaticComponent.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/bookingconfirmation/BookingConfirmationView.kt, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-night/colors.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values/strings.xml, uisdk/src/main/res/values/styles.xml
[MOB-4498](https://karhoo.atlassian.net/browse/MOB-4498)
=> removed night mode, synced translations & small fix booking conf

README.md, uisdk/build.gradle
=> Release 1.8.1

uisdk/src/adyen/java/com/karhoo/uisdk/AdyenDropInServicePresenter.kt, uisdk/src/adyen/java/com/karhoo/uisdk/AdyenPaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/adyen/AdyenDropInServicePresenterTest.kt
[MOB-4179](https://karhoo.atlassian.net/browse/MOB-4179)
[Payment] Add a toggle to keep user's card data for next transaction
[MOB-4179]: https://karhoo.atlassian.net/browse/MOB-4179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Payment] Add a toggle to keep user's card data for next transaction

uisdk/src/main/res/layout/uisdk_view_loyalty_view.xml
[MOB-4550](https://karhoo.atlassian.net/browse/MOB-4550)
[MOB-4550]: https://karhoo.atlassian.net/browse/MOB-4550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Loyalty view has now transparent background for balance

uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-pl-rPL/strings.xml, uisdk/src/main/res/values-pl/strings.xml
[MOB-4572](https://karhoo.atlassian.net/browse/MOB-4572)
[MOB-4572]: https://karhoo.atlassian.net/browse/MOB-4572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> updated translations

uisdk/src/main/java/com/karhoo/uisdk/base/dialog/KarhooAlertDialogHelper.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt
[MOB-4575](https://karhoo.atlassian.net/browse/MOB-4575)
[Checkout] Quote reload fails when going back from checkout
[MOB-4575]: https://karhoo.atlassian.net/browse/MOB-4575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4575 [Checkout] Quote reload fails when going back from checkout

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/presenter/CheckoutPresenterTests.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-4581](https://karhoo.atlassian.net/browse/MOB-4581)
MOB-4581 (Android) Add checkout new unit tests
[MOB-4581]: https://karhoo.atlassian.net/browse/MOB-4581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4581 (Android) Add checkout new unit tests

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarView.kt, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-id-rID/strings.xml, uisdk/src/main/res/values-id/strings.xml, uisdk/src/main/res/values-in-rIN/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-ja-rJP/strings.xml, uisdk/src/main/res/values-ja/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values-pl-rPL/strings.xml, uisdk/src/main/res/values-pl/strings.xml, uisdk/src/main/res/values-pt-rBR/strings.xml, uisdk/src/main/res/values-pt-rPT/strings.xml, uisdk/src/main/res/values-ru-rRU/strings.xml, uisdk/src/main/res/values-ru/strings.xml, uisdk/src/main/res/values-th-rTH/strings.xml, uisdk/src/main/res/values-th/strings.xml, uisdk/src/main/res/values-zh-rCN/strings.xml, uisdk/src/main/res/values-zh/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4557](https://karhoo.atlassian.net/browse/MOB-4557)
MOB-4557 [Accessibility] Fix P1 on Ride Planning / Map
[MOB-4557]: https://karhoo.atlassian.net/browse/MOB-4557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4557 [Accessibility] Fix P1 on Ride Planning / Map

uisdk/build.gradle, uisdk/src/adyen/build.gradle, uisdk/src/braintree/build.gradle
[MOB-4593](https://karhoo.atlassian.net/browse/MOB-4593)
MOB-4593 Upgrade Picasso to version 2.8
[MOB-4593]: https://karhoo.atlassian.net/browse/MOB-4593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4593 Upgrade Picasso to version 2.8

app/build.gradle, app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, uisdk/build.gradle, uisdk/src/braintree/java/BraintreePaymentPresenter.kt, uisdk/src/braintree/java/BraintreePaymentView.kt, uisdk/src/main/AndroidManifest.xml, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/payment/BraintreePaymentManager.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenterTest.kt
[MOB-4596](https://karhoo.atlassian.net/browse/MOB-4596)
[MOB-4596]: https://karhoo.atlassian.net/browse/MOB-4596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4596 Restore Braintree implementation

uisdk/src/braintree/res/values/colors.xml, uisdk/src/main/res/values/colors.xml, uisdk/src/main/res/values/strings.xml
[MOB-4601](https://karhoo.atlassian.net/browse/MOB-4601)
MOB-4601 Customize braintree colors
[MOB-4601]: https://karhoo.atlassian.net/browse/MOB-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4601 Customize braintree colors

app/src/main/java/com/karhoo/samples/uisdk/dropin/config/AdyenGuestConfig.kt, app/src/main/java/com/karhoo/samples/uisdk/dropin/config/AdyenTokenExchangeConfig.kt, app/src/main/java/com/karhoo/samples/uisdk/dropin/config/BraintreeGuestConfig.kt, app/src/main/java/com/karhoo/samples/uisdk/dropin/config/BraintreeTokenExchangeConfig.kt, app/src/main/java/com/karhoo/samples/uisdk/dropin/config/LoyaltyTokenConfig.kt, app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
[MOB-4388](https://karhoo.atlassian.net/browse/MOB-4388)
[MOB-4388]: https://karhoo.atlassian.net/browse/MOB-4388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4388 adapt client app to DP integrations

uisdk/src/braintree/java/BraintreePaymentView.kt
[MOB-4649](https://karhoo.atlassian.net/browse/MOB-4649)
[Add screenshots if any f
or changes you have made to the App/UI]
[MOB-4649]: https://karhoo.atlassian.net/browse/MOB-4649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4649 enable save card switch

app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-fr/strings.xml, uisdk/src/main/res/drawable/uisdk_loyalty_background.xml, uisdk/src/main/res/layout/uisdk_view_legal_notice.xml, uisdk/src/main/res/values/styles.xml
[MOB-4388](https://karhoo.atlassian.net/browse/MOB-4388)
[MOB-4388]: https://karhoo.atlassian.net/browse/MOB-4388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4388 additional small changes

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewContract.kt
[MOB-4678](https://karhoo.atlassian.net/browse/MOB-4678)
[MOB-4678]: https://karhoo.atlassian.net/browse/MOB-4678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4678   Improve address layout component to use ASAP minutes

uisdk/src/braintree/java/BraintreePaymentPresenter.kt, uisdk/src/braintree/java/BraintreePaymentView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenterTest.kt
[MOB-4649](https://karhoo.atlassian.net/browse/MOB-4649)
[MOB-4649]: https://karhoo.atlassian.net/browse/MOB-4649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4649 added Cardholder name required

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt, uisdk/src/main/res/layout/uisdk_view_address_picker.xml
[MOB-4665](https://karhoo.atlassian.net/browse/MOB-4665)
[MOB-4665]: https://karhoo.atlassian.net/browse/MOB-4665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4665 Provide hiding capability for the calendar button on the Address picker

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingModeMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingModeView.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerPresenterTest.kt
[MOB-4666](https://karhoo.atlassian.net/browse/MOB-4666)
[MOB-4666]: https://karhoo.atlassian.net/browse/MOB-4666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4666 Adapt the UX flow to schedule a ride for later

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt
[MOB-4609](https://karhoo.atlassian.net/browse/MOB-4609)
[MOB-4609]: https://karhoo.atlassian.net/browse/MOB-4609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4609 Fix Android drop-in while changing login flows

uisdk/src/braintree/java/BraintreePaymentPresenter.kt
[MOB-4697](https://karhoo.atlassian.net/browse/MOB-4697)
[MOB-4697]: https://karhoo.atlassian.net/browse/MOB-4697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4697 remove cardholder field from drop-in

uisdk/src/braintree/java/BraintreePaymentPresenter.kt, uisdk/src/braintree/java/BraintreePaymentView.kt
[MOB-4714](https://karhoo.atlassian.net/browse/MOB-4714)
[MOB-4714]: https://karhoo.atlassian.net/browse/MOB-4714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4714 stop saving card via backend

uisdk/src/main/java/com/karhoo/uisdk/base/BaseActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingModeMVP.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingModeView.kt, uisdk/src/main/res/anim/kh_slide_down.xml, uisdk/src/main/res/anim/kh_slide_up.xml, uisdk/src/main/res/layout/uisdk_activity_booking_content.xml, uisdk/src/main/res/layout/uisdk_view_booking_mode.xml, uisdk/src/main/res/values/dimens.xml
[MOB-4700](https://karhoo.atlassian.net/browse/MOB-4700)
Add show/hide animation for the booking mode view
[MOB-4700]: https://karhoo.atlassian.net/browse/MOB-4700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4700 Add show/hide animation for the booking mode view

uisdk/src/braintree/res/values/colors.xml, uisdk/src/braintree/res/values/styles.xml
[MOB-4674](https://karhoo.atlassian.net/browse/MOB-4674)
[MOB-4674]: https://karhoo.atlassian.net/browse/MOB-4674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4674   Switch farechoice to use the braintree payment provider instead of Adyen in Sandbox

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, uisdk/src/braintree/AndroidManifest.xml, uisdk/src/debug/AndroidManifest.xml, uisdk/src/main/res/values/styles.xml
[MOB-4609](https://karhoo.atlassian.net/browse/MOB-4609)
[MOB-4609]: https://karhoo.atlassian.net/browse/MOB-4609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4609 Fixed buttons placements for Farechoice

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/legalnotice/LegalNoticeContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/legalnotice/LegalNoticeView.kt, uisdk/src/main/res/layout/uisdk_view_legal_notice.xml
[MOB-4626](https://karhoo.atlassian.net/browse/MOB-4626)
[MOB-4626]: https://karhoo.atlassian.net/browse/MOB-4626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4626 Make Legal notice accordeon always open on Android

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt
[MOB-4682](https://karhoo.atlassian.net/browse/MOB-4682)
MOB-4682 Use DP-injected data to set the date, time and locations
[MOB-4682]: https://karhoo.atlassian.net/browse/MOB-4682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4682 Use DP-injected data to set the date, time and locations

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-4679](https://karhoo.atlassian.net/browse/MOB-4679)
[MOB-4679]: https://karhoo.atlassian.net/browse/MOB-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4679 Incorect text on Checkout button ("Next" instead of "Pay")

uisdk/src/braintree/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentActivity.kt
[MOB-4760](https://karhoo.atlassian.net/browse/MOB-4760)
[MOB-4760]: https://karhoo.atlassian.net/browse/MOB-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4760 Braintree Android 9/10 Close Bug

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragmentContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/fragment/QuotesFragmentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/quotes/mocks/QuotesListViewMock.kt
[MOB-4755](https://karhoo.atlassian.net/browse/MOB-4755)
[MOB-4755]: https://karhoo.atlassian.net/browse/MOB-4755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4755 Lost capability to sort quotes by ETA

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt
[MOB-4749](https://karhoo.atlassian.net/browse/MOB-4749)
[MOB-4749]: https://karhoo.atlassian.net/browse/MOB-4749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4749 Selecting a country dismisses the passenger details screen

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/fragment/CheckoutFragment.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/component/views/CheckoutViewPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsView.kt
[MOB-4756](https://karhoo.atlassian.net/browse/MOB-4756)
[MOB-4756]: https://karhoo.atlassian.net/browse/MOB-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4756 Passenger details are saved on back pressed

README.md, uisdk/build.gradle, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-id-rID/strings.xml, uisdk/src/main/res/values-id/strings.xml, uisdk/src/main/res/values-in-rIN/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-ja-rJP/strings.xml, uisdk/src/main/res/values-ja/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values-pl-rPL/strings.xml, uisdk/src/main/res/values-pl/strings.xml, uisdk/src/main/res/values-pt-rBR/strings.xml, uisdk/src/main/res/values-pt-rPT/strings.xml, uisdk/src/main/res/values-ru-rRU/strings.xml, uisdk/src/main/res/values-ru/strings.xml, uisdk/src/main/res/values-th-rTH/strings.xml, uisdk/src/main/res/values-th/strings.xml, uisdk/src/main/res/values-zh-rCN/strings.xml, uisdk/src/main/res/values-zh/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4730](https://karhoo.atlassian.net/browse/MOB-4730)
[MOB-4730]: https://karhoo.atlassian.net/browse/MOB-4730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4730 Release UISDK 1.12.0

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt
[MOB-4728](https://karhoo.atlassian.net/browse/MOB-4728)
[MOB-4728]: https://karhoo.atlassian.net/browse/MOB-4728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4728 Map pins not centered on Android

uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/base/BaseActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/base/listener/ErrorView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/FeatureFlagsProvider.kt
As Karhoo, I want to be able to display a message when a feature is not available
[MOB-4752](https://karhoo.atlassian.net/browse/MOB-4752)
[MOB-4752]: https://karhoo.atlassian.net/browse/MOB-4752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4752 As Karhoo, I want to be able to display a message when a feature is not available

feature_flag.json, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/KarhooUISDK.kt, uisdk/src/main/java/com/karhoo/uisdk/base/BaseActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/base/listener/ErrorView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/map/BookingMapView.kt, uisdk/src/main/java/com/karhoo/uisdk/util/FeatureFlagsProvider.kt
[MOB-4738](https://karhoo.atlassian.net/browse/MOB-4738)
[MOB-4738]: https://karhoo.atlassian.net/browse/MOB-4738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4738 Create FeatureFlagsProvider class in the UISDK that holds the feature flags

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/BookingActivity.kt
[MOB-4788](https://karhoo.atlassian.net/browse/MOB-4788)
[MOB-4788]: https://karhoo.atlassian.net/browse/MOB-4788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4788 Erase pins, route and buttons from Ride Planning after a booking is done

feature_flag.json, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/util/FeatureFlagsProvider.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyViewPresenterTest.kt
[MOB-4775](https://karhoo.atlassian.net/browse/MOB-4775)
[MOB-4775]: https://karhoo.atlassian.net/browse/MOB-4775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4775 Merge FeatureFlags & LoyaltyFeatureFlags

app/src/main/java/com/karhoo/samples/uisdk/dropin/config/BraintreeTokenExchangeConfig.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/legalnotice/LegalNoticeView.kt, uisdk/src/main/res/color/kh_uisdk_quote_list_filter_chips.xml, uisdk/src/main/res/color/kh_uisdk_quote_list_filter_chips_border.xml, uisdk/src/main/res/color/kh_uisdk_quote_list_filter_chips_text.xml, uisdk/src/main/res/drawable/kh_uisdk_ic_minus_colored.xml, uisdk/src/main/res/drawable/kh_uisdk_ic_plus_colored.xml, uisdk/src/main/res/drawable/kh_uisdk_quote_sort_radio_button_checked.xml, uisdk/src/main/res/layout/fragment_checkout_travel_details_bottom_sheet.xml, uisdk/src/main/res/values-night/colors.xml, uisdk/src/main/res/values/colors.xml, uisdk/src/main/res/values/styles.xml
[MOB-4444](https://karhoo.atlassian.net/browse/MOB-4444)
[MOB-4444]: https://karhoo.atlassian.net/browse/MOB-4444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4444 improve contrast recent screens

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsContract.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/passengerdetails/PassengerDetailsView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/traveldetails/CheckoutTravelDetailsBottomSheet.kt, uisdk/src/main/res/layout/fragment_checkout_comment_bottom_sheet.xml, uisdk/src/main/res/layout/fragment_checkout_travel_details_bottom_sheet.xml, uisdk/src/main/res/layout/uisdk_view_booking_comments.xml, uisdk/src/main/res/layout/uisdk_view_booking_passenger_details.xml
[MOB-4522](https://karhoo.atlassian.net/browse/MOB-4522)
[MOB-4522]: https://karhoo.atlassian.net/browse/MOB-4522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4522 Improve Android text field components

uisdk/src/main/java/com/karhoo/uisdk/screen/address/static/AddressStaticComponent.kt
[MOB-4810](https://karhoo.atlassian.net/browse/MOB-4810)
[MOB-4810]: https://karhoo.atlassian.net/browse/MOB-4810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4810 read only first part od address, avoid duplicates

uisdk/src/main/java/com/karhoo/uisdk/screen/address/static/AddressStaticComponent.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/StringExt.kt
[MOB-4653](https://karhoo.atlassian.net/browse/MOB-4653)
[MOB-4653]: https://karhoo.atlassian.net/browse/MOB-4653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4653 remove duplicates from static address component

uisdk/src/main/java/com/karhoo/uisdk/screen/address/static/AddressStaticComponent.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailView.kt, uisdk/src/main/res/values-de-rDE/strings.xml, uisdk/src/main/res/values-de/strings.xml, uisdk/src/main/res/values-en-rGB/strings.xml, uisdk/src/main/res/values-es-rES/strings.xml, uisdk/src/main/res/values-es/strings.xml, uisdk/src/main/res/values-fr-rFR/strings.xml, uisdk/src/main/res/values-fr/strings.xml, uisdk/src/main/res/values-id-rID/strings.xml, uisdk/src/main/res/values-id/strings.xml, uisdk/src/main/res/values-in-rIN/strings.xml, uisdk/src/main/res/values-it-rIT/strings.xml, uisdk/src/main/res/values-it/strings.xml, uisdk/src/main/res/values-ja-rJP/strings.xml, uisdk/src/main/res/values-ja/strings.xml, uisdk/src/main/res/values-nl-rNL/strings.xml, uisdk/src/main/res/values-nl/strings.xml, uisdk/src/main/res/values-pl-rPL/strings.xml, uisdk/src/main/res/values-pl/strings.xml, uisdk/src/main/res/values-pt-rBR/strings.xml, uisdk/src/main/res/values-pt-rPT/strings.xml, uisdk/src/main/res/values-ru-rRU/strings.xml, uisdk/src/main/res/values-ru/strings.xml, uisdk/src/main/res/values-th-rTH/strings.xml, uisdk/src/main/res/values-th/strings.xml, uisdk/src/main/res/values-zh-rCN/strings.xml, uisdk/src/main/res/values-zh/strings.xml, uisdk/src/main/res/values/strings.xml
[MOB-4587](https://karhoo.atlassian.net/browse/MOB-4587)
[MOB-4587]: https://karhoo.atlassian.net/browse/MOB-4587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4587 add address type prefix to all displayed addresses

uisdk/src/braintree/java/BraintreePaymentPresenter.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/payment/braintree/BraintreePaymentPresenterTest.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/checkout/view/CheckoutViewPresenterTests.kt
[MOB-4739](https://karhoo.atlassian.net/browse/MOB-4739)
[MOB-4739]: https://karhoo.atlassian.net/browse/MOB-4739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4739   [Braintree] Remove legacy requests in UI and network SDK

uisdk/src/braintree/java/BraintreePaymentPresenter.kt
[MOB-4735](https://karhoo.atlassian.net/browse/MOB-4735)
[MOB-4735]: https://karhoo.atlassian.net/browse/MOB-4735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4735 allow to remove card

app/build.gradle, app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, app/src/main/java/com/karhoo/samples/uisdk/dropin/config/LoyaltyTokenBraintreeConfig.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml
[MOB-4822](https://karhoo.atlassian.net/browse/MOB-4822)
[MOB-4822]: https://karhoo.atlassian.net/browse/MOB-4822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4822 Add Braintree loyalty

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarView.kt, uisdk/src/main/res/layout/uisdk_view_address_picker.xml, uisdk/src/main/res/layout/uisdk_view_contact_options.xml, uisdk/src/main/res/layout/uisdk_view_past_ride_card.xml, uisdk/src/main/res/layout/uisdk_view_quotes_item.xml, uisdk/src/main/res/layout/uisdk_view_ride_detail.xml, uisdk/src/main/res/layout/uisdk_view_upcoming_ride_card.xml
[MOB-4512](https://karhoo.atlassian.net/browse/MOB-4512)
[MOB-4512]: https://karhoo.atlassian.net/browse/MOB-4512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4512 Change label color & accent color of *old* UI SDK screens

app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, uisdk/src/main/java/com/karhoo/uisdk/KarhooUISDK.kt, uisdk/src/main/java/com/karhoo/uisdk/base/featureFlags/FeatureFlagsService.kt, uisdk/src/test/java/com/karhoo/uisdk/featureFlags/FeatureFlagsTest.kt
[MOB-4811](https://karhoo.atlassian.net/browse/MOB-4811)
[MOB-4811]: https://karhoo.atlassian.net/browse/MOB-4811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4811   Align feature flags between platforms

uisdk/src/main/java/com/karhoo/uisdk/screen/booking/quotes/list/QuotesListItemView.kt
[MOB-4748](https://karhoo.atlassian.net/browse/MOB-4748)
[MOB-4748]: https://karhoo.atlassian.net/browse/MOB-4748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4748   Vehicle type mis-match on the quote list

README.md, uisdk/build.gradle
[MOB-4850](https://karhoo.atlassian.net/browse/MOB-4850)
[MOB-4850]: https://karhoo.atlassian.net/browse/MOB-4850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4850 UI SDK 1.13.0 release

README.md, feature_flag.json, uisdk/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/base/BaseActivity.kt
[MOB-4786](https://karhoo.atlassian.net/browse/MOB-4786)
[MOB-4786]: https://karhoo.atlassian.net/browse/MOB-4786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4786 Hotfix release for Adyen Check

feature_flag.json
[MOB-4786](https://karhoo.atlassian.net/browse/MOB-4786)
[MOB-4786]: https://karhoo.atlassian.net/browse/MOB-4786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4786 Update JSON on our repository to trigger the warning message and disable Adyen

README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/karhoo/samples/uisdk/dropin/MainActivity.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties, uisdk/build.gradle, uisdk/src/adyen/build.gradle, uisdk/src/braintree/build.gradle, uisdk/src/main/java/com/karhoo/uisdk/base/validator/PhoneNumberValidator.kt, uisdk/src/main/java/com/karhoo/uisdk/notification/rides/past/RideNotificationView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/address/map/AddressMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/address/addressbar/AddressBarPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyStaticDetails.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/loyalty/LoyaltyView.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/booking/checkout/tripallocation/TripAllocationPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/detail/RideDetailPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/past/card/PastRideCardPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/rides/upcoming/card/UpcomingRideCardPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/deta/DetaPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/screen/trip/map/TripMapPresenter.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/ServiceCancellationExt.kt, uisdk/src/main/java/com/karhoo/uisdk/util/extension/SnackbarExt.kt, uisdk/src/test/java/com/karhoo/uisdk/screen/booking/address/timedatepicker/TimeDatePickerPresenterTest.kt
[MOB-4886](https://karhoo.atlassian.net/browse/MOB-4886)
[MOB-4886]: https://karhoo.atlassian.net/browse/MOB-4886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4886 Braintree Upgrade and Release 1.13.3

README.md, uisdk/build.gradle
[MOB-4904](https://karhoo.atlassian.net/browse/MOB-4904)
[MOB-4904]: https://karhoo.atlassian.net/browse/MOB-4904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-4904 release 1.13.4
